// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7xeWMNPHJvwMorzDrpQRe22dOMmJSwrs',
    appId: '1:613509125472:web:985f47db7efcc08227fa05',
    messagingSenderId: '613509125472',
    projectId: 'amur-restoran',
    authDomain: 'amur-restoran.firebaseapp.com',
    storageBucket: 'amur-restoran.firebasestorage.app',
    measurementId: 'G-G4PSF0HNN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYA3_LPPQ642ZYMTC85FrcznK_WbTvUhE',
    appId: '1:613509125472:android:c30f9adb899496b527fa05',
    messagingSenderId: '613509125472',
    projectId: 'amur-restoran',
    storageBucket: 'amur-restoran.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmwnAEtDw2aNFvX-A2wK_5vZKKXdTn_hE',
    appId: '1:613509125472:ios:dce96306e78498bb27fa05',
    messagingSenderId: '613509125472',
    projectId: 'amur-restoran',
    storageBucket: 'amur-restoran.firebasestorage.app',
    iosBundleId: 'com.example.amurRes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7xeWMNPHJvwMorzDrpQRe22dOMmJSwrs',
    appId: '1:613509125472:web:b193a8d892797e9227fa05',
    messagingSenderId: '613509125472',
    projectId: 'amur-restoran',
    authDomain: 'amur-restoran.firebaseapp.com',
    storageBucket: 'amur-restoran.firebasestorage.app',
    measurementId: 'G-ZBRPB665B9',
  );
}
